Extracting questions 20 to 29
INSERT INTO questions (id, year, statement, options, correct_answer, chapter, book_section) VALUES
('db78a600-d69a-45c4-947e-73694e1d8940', 2025, 'Analise o caso clinico a seguir. Paciente do sexo feminino, 30 anos de idade, refere aparecimento de lesões hiperpigmentadas nas áreas de exposição solar, acompanhadas de artralgia. Exames laboratoriais evidenciaram presença de autoanticorpos anti-RO-ssA. A paciente refere uso de diversas medicações prévias ao aparecimento das lesões. Considerando esse caso clínico, assinale a alternativa correta.', '["Cerca de 50% dos casos evoluem para doença sistêmica.","Hidroclorotiazida é droga pouco associada ao desenvolvimento de lesões.","Positividade para mais de um autoanticorpo diminui a chance de doença sistêmica.","Anti-TNF-alfa é o imunobiológico de escolha para tratamento desta forma da doença."]', 'A', 'Lúpus Eritematoso', 'TED - Parte 2'),
('d1a04a09-6dfd-4e82-939f-16c2ed22718e', 2025, 'Analise o caso clínico a seguir. Paciente do sexo masculino, 45 anos de idade, refere aparecimento espontâneo de dor súbita, acompanhada de edema e eritema das extremidades, rapidamente progredindo para rigidez e contraturas articulares de punhos, joelhos e cotovelos. A induração da pele formou sulcos nos trajetos venosos superficiais. Fenômeno de Raynaud está ausente e o exame laboratorial mostra aldolase elevada. Considerando esse caso clínico, qual é o diagnóstico?', '["Esclerose sistêmica.","Celulite eosinofílica.","Escleromixedema.","Fasciite eosinofílica."]', 'D', 'Fasciite Eosinofílica', 'TED - Parte 2'),
('8bc7bbfd-7bb4-47b5-b7c7-5c258b4b035e', 2025, 'Paciente do sexo feminino, 33 anos de idade, refere lesões eritematosas psoriasiformes nas áreas reticuladas nas axilas e região inguinocrural, associadas a pápulas amarronzadas nessas mesmas localizações. Apresenta lesões foliculares hiperqueratóticas na nuca, similares a comedões. Considerando esse caso clínico, qual é o diagnóstico?', '["Acropigmentação reticulada de Kitamura.","Doença de Dowling-Degos.","Discromatose simétrica hereditária.","Contaminação pelo arsênico."]', 'B', 'Discromias Congênitas, Hereditárias e Adquiridas – Hipercromias', 'TED - Parte 2'),
('fb111d50-88d8-4f31-8182-dbdf1884a59f', 2025, 'Com relação às dermatoses perfurantes, analise as afirmativas a seguir. I. Na elastose perfurante sergipinosa, o material que é extruído é tecido elástico II. Em pacientes com insuficiência renal crônica, o transplante renal pode melhorar a dermatose III. A condrodermatite nodular da hélice é uma dermatose perfurante secundária', '["I, apenas.","II, apenas.","III, apenas.","I, II e III."]', 'D', 'Distúrbios Atróficos e Escleróticos', 'TED - Parte 2'),
('cd974b00-41aa-46d9-acc2-cab2ded4e01d', 2025, 'Paciente do sexo masculino, 60 anos de idade, apresenta hipermobilidade das articulações e uma pele hiperextensivel, hiperelástica e frágil, apresentando várias cicatrizes atróficas nos joelhos e cotovelos com aspecto de "papel de cigarro". Refere ter tido subluxações no quadril e não foram observadas alterações cardíacas ou na aorta, assim como nenhuma alteração respiratória ou pulmonar. Avaliação genética, após avaliação dos casos na familia, mostrou evidente padrão autossômico dominante. Considerando esse caso clínico, qual é o diagnóstico?', '["Pseudoxantoma elástico.","Síndrome de Ehlers-Danlos clássica.","Síndrome de Marfan.","Cútis laxa."]', 'B', 'Genodermatoses Mesenquimais', 'TED - Parte 8'),
('49e567f1-d1ab-48e2-89dc-7aa7cb59fc42', 2025, 'Com relação às hipertrofias dérmicas, correlacione a COLUNA II com a COLUNA I, associando cada tipo com sua característica.', '["2, 3, 4, 1","3, 2, 1, 4","1, 3, 2, 4","3, 4, 2, 1"]', 'B', 'Princípios Básicos da Dermatopatologia', 'TED - Parte 1'),
('697667c9-576a-4975-8afc-20427537a88e', 2025, 'Com relação aos agentes antissépticos, assinale a alternativa correta.', '["A iodopovidina pode produzir urticária de contato.","A clorexidina pode produzir queratite devido à exposição ocular.","O álcool isopropílico apresenta forte atividade antimicrobiana.","O peróxido de hidrogênio é inofensivo aos queratinócitos in vitro."]', 'B', 'Esterilização, Desinfecção e Antissepsia na Prática Dermatológica', 'TED - Parte 11'),
('4fea73af-e3b6-40e1-81ec-3437ee82f0c3', 2025, 'Analise a imagem a seguir na qual estão assinalados os pontos de emergência de alguns nervos sensitivos da face. Considerando a imagem, assinale a alternativa correta.', '["O nervo representado pelo número 2 emerge lateral ao forame supraorbital.","O nervo representado pelo número 3 é ramo do nervo etmoidal externo.","O nervo representado pelo número 5 origina-se do ramo maxilar do nervo trigêmeo.","O nervo representado pelo número 6 é ramo terminal do nervo mandibular."]', 'D', 'Fundamentos da Anatomia Cirúrgica Tegumentar', 'TED - Parte 11'),
('d0c9a0dc-4138-4a9f-97a0-93522c8f1299', 2025, 'Com relação à M-plastia, assinale a alternativa correta.', '["O resultado, após a sutura, é em forma de M.","O procedimento é particularmente útil em locais da pele que não são planos.","A técnica deve ser utilizada somente em uma das extremidades da ferida operatória.","As bases dos triângulos são removidas num ângulo de 90 graus com a linha de sutura."]', 'B', 'Técnicas em Cirurgia Dermatológica Básica', 'TED - Parte 11'),
('c6b79cbd-2d48-44ff-a2e7-65b80e5f9aa1', 2025, 'Analise o caso clínico a seguir. Paciente do sexo feminino, 60 anos de idade, apresentando carcinoma basocelular infiltrativo no dorso nasal, foi submetida à cirurgia micrográfica, resultando em um defeito subtotal do nariz, envolvendo perda do dorso e ponta nasal, com preservação da cartilagem. Considerando esse caso clínico, qual é o retalho indicado para a reconstrução?', '["Nasal, de Rieger.","Melolabial, de interpolação.","Nasolabial invertido, de Spear.","Paramediano, da região frontal."]', 'D', 'Enxertos e Retalhos Cutâneos', 'TED - Parte 11');
